version: '1.0'
services:
    db:
        image: mysql
        cap_add:
            - SYS_NICE
        restart: always
        environment:
            - MYSQL_DATABASE=forjava
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
        volumes:
            - db:/var/lib/mysql
            - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
            
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080

volumes:
    db:
        driver: local
